# Generated by Django 4.2.9 on 2024-03-14 06:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0002_remove_email_email_host_remove_email_email_port_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="email",
            name="email_host_port",
            field=models.SmallIntegerField(default=587),
        ),
        migrations.AddField(
            model_name="email",
            name="email_host_smtp_host",
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="email",
            name="email_host_use_tls",
            field=models.BooleanField(default=True),
        ),
    ]
