# Generated by Django 4.2.9 on 2024-03-14 06:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0003_email_email_host_port_email_email_host_smtp_host_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Email",
        ),
    ]
