# Generated by Django 4.2.9 on 2024-03-14 06:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("base", "0004_delete_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="Email",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_host_user", models.CharField(max_length=255)),
                ("email_host_password", models.CharField(max_length=255)),
                ("email_host_port", models.SmallIntegerField(default=587)),
                ("email_host_smtp_host", models.CharField(max_length=255)),
                ("email_host_use_tls", models.BooleanField(default=True)),
            ],
        ),
    ]
