# Generated by Django 5.0.3 on 2024-03-15 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_email_today_email_sent_scheduledemail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('subject', models.TextField(blank=True, null=True)),
                ('body', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='scheduledemail',
            name='body',
        ),
        migrations.RemoveField(
            model_name='scheduledemail',
            name='subject',
        ),
        migrations.AddField(
            model_name='scheduledemail',
            name='attached_campaign',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='base.campaign'),
            preserve_default=False,
        ),
    ]
