# Generated by Django 5.0.3 on 2024-03-15 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_scheduledemail_attached_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='base_time_gap',
            field=models.SmallIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='from_emails',
            field=models.ManyToManyField(to='base.email'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='random_time_gap',
            field=models.SmallIntegerField(blank=True, default=1, null=True),
        ),
    ]
