# Generated by Django 5.0.3 on 2024-03-15 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_campaign_base_time_gap_campaign_from_emails_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
            ],
        ),
    ]
