# Generated by Django 5.0.3 on 2024-03-15 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_testemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='to_emails',
            field=models.ManyToManyField(to='base.testemail'),
        ),
    ]
