# Generated by Django 5.0.3 on 2024-03-15 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_campaign_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('Stop', 'Stop'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Stop', max_length=20),
        ),
    ]
