# Generated by Django 5.0.3 on 2024-03-16 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_campaign_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
