# Generated by Django 5.0.3 on 2024-03-16 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_remove_campaign_verified_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledemail',
            name='captured_by_celery',
            field=models.BooleanField(default=False),
        ),
    ]
