# Generated by Django 5.0.3 on 2024-03-19 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_scheduledemail_captured_by_celery'),
        ('django_celery_beat', '0018_improve_crontab_helptext'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledemail',
            name='captured_by_celery',
        ),
        migrations.RemoveField(
            model_name='scheduledemail',
            name='time_to_send',
        ),
        migrations.AddField(
            model_name='scheduledemail',
            name='task_attached',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.periodictask'),
        ),
    ]
