# Generated by Django 5.0.3 on 2024-03-19 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_remove_scheduledemail_captured_by_celery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledemail',
            name='sent',
            field=models.BooleanField(default=False),
        ),
    ]
