# Generated by Django 5.0.3 on 2024-03-20 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_rename_user_emial_email_connected_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='connected_user_email',
            new_name='user_id',
        ),
    ]
