# Generated by Django 5.0.3 on 2024-03-22 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_remove_email_email_working'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='user_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='scheduledemail',
            name='user_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
