# Generated by Django 5.0.3 on 2024-03-23 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_campaign_user_id_scheduledemail_user_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestEmail',
            new_name='SendToEmails',
        ),
    ]
