# Generated by Django 5.0.3 on 2024-03-23 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_rename_testemail_sendtoemails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SendToEmails',
            new_name='SendToEmail',
        ),
    ]
