# Generated by Django 5.0.3 on 2024-03-23 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_rename_sendtoemails_sendtoemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendtoemail',
            name='email',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
