# Generated by Django 5.0.3 on 2024-03-23 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_alter_sendtoemail_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendtoemail',
            name='email',
            field=models.CharField(max_length=255),
        ),
    ]
