# Generated by Django 5.0.3 on 2024-03-23 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_alter_sendtoemail_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='today_email_sent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='total_email_sent',
            field=models.IntegerField(default=0),
        ),
    ]
